/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBookModal: typeof import('./components/AddBookModal.vue')['default']
    BookCard: typeof import('./components/BookCard.vue')['default']
    BookForm: typeof import('./components/BookForm.vue')['default']
    BookGrid: typeof import('./components/BookGrid.vue')['default']
    CoverImage: typeof import('./components/CoverImage.vue')['default']
    ExportButton: typeof import('./components/ExportButton.vue')['default']
    FilterBar: typeof import('./components/FilterBar.vue')['default']
    NewReleaseBanner: typeof import('./components/NewReleaseBanner.vue')['default']
    RatingDisplay: typeof import('./components/RatingDisplay.vue')['default']
    RatingInput: typeof import('./components/RatingInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesRow: typeof import('./components/SeriesRow.vue')['default']
    StatsChart: typeof import('./components/StatsChart.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    TagChip: typeof import('./components/TagChip.vue')['default']
  }
}
